services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}

  frontend:
    build: ./frontend
    ports:
      - "3000:8080"
    depends_on:
      - backend
